Update update-readme.yml

diff --git a/.github/workflows/update-readme.yml b/.github/workflows/update-readme.yml
--- a/.github/workflows/update-readme.yml
+++ b/.github/workflows/update-readme.yml
@@ -17,14 +17,15 @@ jobs:
   printInputs:
     runs-on: ubuntu-latest
     steps:
-      - name: Run
+      - name: Run With Error
+        if: ${{ github.event.inputs.tags }} == 'error'
+        run: |
+          echo "Error!" > logfile.log
+          exit 125
+        
+      - name: Run without error
+        if: ${{ github.event.inputs.tags }} != 'error'
         run: |
           echo "Log level: ${{ github.event.inputs.logLevel }}"
           sleep 60
           echo "Tags: ${{ github.event.inputs.tags }}"
-          a = ${{ github.event.inputs.tags }}
-          b = "error"
-          if [ "$a" == "$b" ]; then
-            echo "Error!" > logfile.log
-            exit 125
-          fi
